# Generated by Django 2.2.4 on 2019-08-28 18:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Actividad')),
                ('state', models.CharField(choices=[('a', 'BORRADOR'), ('b', 'EN CURSO'), ('c', 'TERMINADA')], default='a', max_length=1, verbose_name='Estado')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', ckeditor.fields.RichTextField(blank=True, verbose_name='Dirección')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Projecto',
                'verbose_name_plural': 'Projectos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Tarea')),
                ('state', models.FloatField(default=0, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('alta', 'ALTA'), ('media', 'MEDIA'), ('baja', 'BAJA')], default='alta', max_length=6, verbose_name='Prioridad')),
                ('estimated_time', models.TimeField(verbose_name='Tiempo estimado')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('activities', models.ManyToManyField(related_name='get_tasks', to='task.Activity', verbose_name='Actividades')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Project', verbose_name='Proyecto')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ('name',),
            },
        ),
    ]
